/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exhibits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exhibits */
        get: operations["exhibits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exhibits/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exhibit */
        get: operations["exhibit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guide */
        post: operations["guide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/evidence/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Guide Evidence */
        get: operations["inspect_guide_evidence_api_v1_guide_evidence__identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regions */
        get: operations["regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session"];
        put?: never;
        /** Start Session */
        post: operations["start_session"];
        /** Delete Session */
        delete: operations["delete_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["root_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerSection */
        AnswerSection: {
            /** Claim Ids */
            claim_ids?: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "conversation" | "evidence" | "general";
            /** Section Id */
            section_id: string;
            /**
             * Support Label
             * @enum {string}
             */
            support_label: "sources_checked" | "official_lookup" | "general_unverified" | "conversation";
            /** Text */
            text: string;
        };
        /** ArtifactCard */
        ArtifactCard: {
            /** Catalog Date */
            catalog_date: string;
            /** Current Location */
            current_location: string;
            /** Id */
            id: string;
            /** Image Hashes */
            image_hashes: string[];
            /** Medium */
            medium: string;
            /** Origin */
            origin: {
                [key: string]: string;
            };
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
        };
        /** ArtifactList */
        ArtifactList: {
            /** Items */
            items: components["schemas"]["ArtifactCard"][];
        };
        /** ClaimCard */
        ClaimCard: {
            /** Id */
            id: string;
            /** Passage Ids */
            passage_ids: string[];
            /** Text */
            text: string;
        };
        /** ConversationChoice */
        ConversationChoice: {
            /**
             * Intent
             * @enum {string}
             */
            intent: "greeting" | "identity" | "thanks" | "start" | "goodbye" | "help" | "empathy" | "clarification";
            /** Invitation Id */
            invitation_id?: number | null;
            /**
             * Locale
             * @enum {string}
             */
            locale: "en" | "zh-CN";
            /** Opening Id */
            opening_id: number;
        };
        /** ConversationPair */
        ConversationPair: {
            /** Assistant */
            assistant: string;
            /** User */
            user: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
            /** Request Id */
            request_id: string;
        };
        /** EvidencePassage */
        EvidencePassage: {
            /** Canonical Url */
            canonical_url: string;
            /**
             * Classification
             * @default source_statement
             * @enum {string}
             */
            classification: "source_statement" | "history" | "interpretation" | "folklore" | "creative_adaptation";
            /** Content Hash */
            content_hash: string;
            /**
             * Evidence Origin
             * @default reviewed_corpus
             * @enum {string}
             */
            evidence_origin: "reviewed_corpus" | "reviewed_unit" | "official_lookup" | "diagnostic_candidate";
            /** Exhibit Ids */
            exhibit_ids: string[];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Institution */
            institution: string;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "zh-CN";
            /** Locator */
            locator: string;
            /** Passage Id */
            passage_id: string;
            /** Region Ids */
            region_ids: string[];
            /** Required Support Ids */
            required_support_ids?: string[];
            /** Review Id */
            review_id: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewer */
            reviewer: string;
            /** Rights Basis */
            rights_basis: string;
            /** Source Id */
            source_id: string;
            /** Source Title */
            source_title: string;
            /** Statement Variants */
            statement_variants?: string[];
            /** Text */
            text: string;
        };
        /** ExhibitCard */
        ExhibitCard: {
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Id */
            id: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "en" | "zh-CN";
            /** Region Ids */
            region_ids: string[];
            /** Summary */
            summary: string;
            /** Themes */
            themes: string[];
            /** Title */
            title: string;
        };
        /** ExhibitDetail */
        ExhibitDetail: {
            /** Claims */
            claims: components["schemas"]["ClaimCard"][];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Id */
            id: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "en" | "zh-CN";
            /** Region Ids */
            region_ids: string[];
            review: components["schemas"]["ReviewInfo"];
            /** Sources */
            sources: components["schemas"]["SourceCard"][];
            /** Summary */
            summary: string;
            /** Themes */
            themes: string[];
            /** Title */
            title: string;
        };
        /** ExhibitPage */
        ExhibitPage: {
            /** Items */
            items: components["schemas"]["ExhibitCard"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** GuideAnswer */
        GuideAnswer: {
            /** Answer Claim Ids */
            answer_claim_ids?: string[];
            /** Answer Id */
            answer_id: string;
            /** Answer Text */
            answer_text: string;
            /** Claims */
            claims?: components["schemas"]["ValidatedClaim"][];
            /** Context Claim Ids */
            context_claim_ids?: string[];
            /** Context Token */
            context_token?: string | null;
            /** Contract Version */
            contract_version?: "hybrid_sections_v1" | null;
            conversation_choice?: components["schemas"]["ConversationChoice"] | null;
            /** Corpus Version */
            corpus_version: string;
            /** Coverage Limit */
            coverage_limit: string;
            /** Database Ms */
            database_ms?: number | null;
            /**
             * Depth
             * @enum {string}
             */
            depth: "concise" | "beginner" | "deeper";
            /** Embedding Encoder Version */
            embedding_encoder_version?: string | null;
            /** Embedding Model Version */
            embedding_model_version?: string | null;
            /**
             * Embedding Status
             * @default disabled
             */
            embedding_status: string;
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Generation Ms */
            generation_ms?: number | null;
            /**
             * Harness Version
             * @default guide-hybrid-sections-v6
             */
            harness_version: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "en" | "zh-CN";
            /**
             * Lookup Status
             * @default not_requested
             */
            lookup_status: string;
            /**
             * Mode
             * @default live
             * @constant
             */
            mode: "live";
            /**
             * Personality Version
             * @default jinyao-conversation-v2
             */
            personality_version: string;
            /**
             * Presentation Version
             * @default attributed_excerpt_v1
             * @enum {string}
             */
            presentation_version: "attributed_excerpt_v1" | "inventory_projection_v1" | "conversation_composition_v1" | "hybrid_sections_v1";
            /**
             * Prompt Version
             * @default jinyao-hybrid-explanations-v6
             */
            prompt_version: string;
            /** Provider Attempt Id */
            provider_attempt_id?: string | null;
            /** Query Embedding Ms */
            query_embedding_ms?: number | null;
            /** Ranking Ms */
            ranking_ms?: number | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "reviewed_excerpt" | "coverage_gap" | "ambiguous_topic" | "unsupported_claim" | "evidence_changed" | "unsafe_source" | "social_turn" | "supported_explanation" | "general_explanation";
            /** Related Exhibit Ids */
            related_exhibit_ids?: string[];
            /**
             * Retrieval Mode
             * @default lexical_only
             * @enum {string}
             */
            retrieval_mode: "lexical_only" | "hybrid";
            /** Retrieval Ms */
            retrieval_ms?: number | null;
            /**
             * Retrieval Version
             * @default lexical-bm25-cjk-v1
             */
            retrieval_version: string;
            /** Sections */
            sections?: components["schemas"]["AnswerSection"][];
            /** Social Intent */
            social_intent?: ("greeting" | "identity" | "thanks" | "start" | "goodbye" | "help" | "empathy" | "clarification") | null;
            /** Sources */
            sources?: components["schemas"]["EvidencePassage"][];
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "insufficient" | "clarification" | "conversational";
            /**
             * Uncertainty
             * @enum {string}
             */
            uncertainty: "partial" | "insufficient";
            /** Validation Ms */
            validation_ms?: number | null;
        };
        /** GuideEvidenceState */
        GuideEvidenceState: {
            /** Current */
            current: boolean;
            passage?: components["schemas"]["EvidencePassage"] | null;
        };
        /** GuideRequest */
        GuideRequest: {
            /**
             * Context Consent
             * @default false
             */
            context_consent: boolean;
            /** Context Token */
            context_token?: string | null;
            /** Conversation */
            conversation?: components["schemas"]["ConversationPair"][];
            /**
             * Depth
             * @default concise
             * @enum {string}
             */
            depth: "concise" | "beginner" | "deeper";
            /** Exhibit Id */
            exhibit_id?: string | null;
            /**
             * Locale
             * @default en
             * @enum {string}
             */
            locale: "en" | "zh-CN";
            /** Question */
            question: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "available" | "unavailable";
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live";
            /**
             * Pgvector
             * @enum {string}
             */
            pgvector: "available" | "unavailable";
            /** Pgvector Version */
            pgvector_version?: string | null;
            /** Postgres Version */
            postgres_version?: string | null;
            /**
             * Schema Status
             * @enum {string}
             */
            schema_status: "current" | "unavailable";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** PassageCard */
        PassageCard: {
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Locator */
            locator: string;
            review: components["schemas"]["ReviewInfo"];
            /** Rights Basis */
            rights_basis: string;
            /** Text */
            text: string;
        };
        /** RegionCard */
        RegionCard: {
            /** Approved Geometry Ref */
            approved_geometry_ref: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** RegionList */
        RegionList: {
            /** Items */
            items: components["schemas"]["RegionCard"][];
        };
        /** ReviewInfo */
        ReviewInfo: {
            /**
             * Kind
             * @default editorial
             * @constant
             */
            kind: "editorial";
            /** Notes */
            notes: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Reviewer */
            reviewer: string;
        };
        /** SessionDeleted */
        SessionDeleted: {
            /**
             * Deleted
             * @default true
             * @constant
             */
            deleted: true;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Behavioral Opt In
             * @default false
             * @constant
             */
            behavioral_opt_in: false;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Session Id */
            session_id: string;
        };
        /** SourceCard */
        SourceCard: {
            /** Canonical Url */
            canonical_url: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Id */
            id: string;
            /** Institution */
            institution: string;
            /** Passages */
            passages: components["schemas"]["PassageCard"][];
            /** Raw Hash */
            raw_hash: string;
            review: components["schemas"]["ReviewInfo"];
            /** Rights Basis */
            rights_basis: string;
            /** Title */
            title: string;
        };
        /** SourceList */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceCard"][];
        };
        /** ValidatedClaim */
        ValidatedClaim: {
            /** Claim Id */
            claim_id: string;
            /**
             * Kind
             * @default source_statement
             * @enum {string}
             */
            kind: "source_statement" | "history" | "interpretation" | "folklore" | "creative_adaptation";
            /** Passage Ids */
            passage_ids: string[];
            /** Source Ids */
            source_ids: string[];
            /**
             * Support Method
             * @default complete_reviewed_passage
             * @enum {string}
             */
            support_method: "complete_reviewed_passage" | "reviewed_variant_v1" | "complete_sentence_v1" | "inventory_projection_v1" | "official_metadata_projection_v1";
            /**
             * Support Version
             * @default deterministic-support-v1
             */
            support_version: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactList"];
                };
            };
        };
    };
    exhibits: {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
                region_id?: string | null;
                themes?: string | null;
                q?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExhibitPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exhibit: {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
            };
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExhibitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideAnswer"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Anonymous session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request or provider limit reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Guide unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inspect_guide_evidence_api_v1_guide_evidence__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideEvidenceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"] | components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    regions: {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    start_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeleted"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"] | components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
