"""content

Revision ID: 0002_content
Revises: 0001_sessions
"""

import sqlalchemy as sa
from alembic import op

revision = "0002_content"
down_revision = "0001_sessions"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("previous_status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_entity_id"), "reviews", ["entity_id"], unique=False)
    op.create_index(op.f("ix_reviews_entity_type"), "reviews", ["entity_type"], unique=False)
    op.create_table(
        "exhibits",
        sa.Column("title", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("themes", sa.JSON(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.CheckConstraint("estimated_minutes BETWEEN 1 AND 60"),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exhibits_status"), "exhibits", ["status"], unique=False)
    op.create_table(
        "regions",
        sa.Column("names", sa.JSON(), nullable=False),
        sa.Column("approved_geometry_ref", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.CheckConstraint("status IN ('draft','approved','rejected','withdrawn')"),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_regions_status"), "regions", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column("rights_basis", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution", "external_id"),
    )
    op.create_index(op.f("ix_sources_status"), "sources", ["status"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("external_object_id", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("catalog_title", sa.Text(), nullable=False),
        sa.Column("catalog_date", sa.Text(), nullable=False),
        sa.Column("medium", sa.Text(), nullable=False),
        sa.Column("origin", sa.JSON(), nullable=False),
        sa.Column("current_location", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution", "external_object_id"),
    )
    op.create_index(op.f("ix_artifacts_source_id"), "artifacts", ["source_id"], unique=False)
    op.create_index(op.f("ix_artifacts_status"), "artifacts", ["status"], unique=False)
    op.create_table(
        "claims",
        sa.Column("exhibit_id", sa.String(length=100), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["exhibit_id"],
            ["exhibits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_exhibit_id"), "claims", ["exhibit_id"], unique=False)
    op.create_index(op.f("ix_claims_status"), "claims", ["status"], unique=False)
    op.create_table(
        "exhibit_regions",
        sa.Column("exhibit_id", sa.String(length=100), nullable=False),
        sa.Column("region_id", sa.String(length=100), nullable=False),
        sa.Column("geographic_role", sa.String(length=20), nullable=False),
        sa.CheckConstraint("geographic_role IN ('practice','origin','context')"),
        sa.ForeignKeyConstraint(
            ["exhibit_id"],
            ["exhibits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("exhibit_id", "region_id"),
    )
    op.create_table(
        "passages",
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("locator", sa.Text(), nullable=False),
        sa.Column("rights_basis", sa.Text(), nullable=False),
        sa.Column("rights_status", sa.String(length=20), nullable=False),
        sa.Column("embedding_version", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_passages_source_id"), "passages", ["source_id"], unique=False)
    op.create_index(op.f("ix_passages_status"), "passages", ["status"], unique=False)
    op.create_table(
        "artifact_exhibits",
        sa.Column("artifact_id", sa.String(length=100), nullable=False),
        sa.Column("exhibit_id", sa.String(length=100), nullable=False),
        sa.Column("evidence_passage_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_passage_id"],
            ["passages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exhibit_id"],
            ["exhibits.id"],
        ),
        sa.PrimaryKeyConstraint("artifact_id", "exhibit_id", "evidence_passage_id"),
    )
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.String(length=100), nullable=False),
        sa.Column("passage_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
        ),
        sa.PrimaryKeyConstraint("claim_id", "passage_id"),
    )
    op.create_table(
        "media",
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("artifact_id", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("rights_code", sa.String(length=30), nullable=False),
        sa.Column("rights_status", sa.String(length=20), nullable=False),
        sa.Column("rights_evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "url"),
    )
    op.create_index(op.f("ix_media_artifact_id"), "media", ["artifact_id"], unique=False)
    op.create_index(op.f("ix_media_source_id"), "media", ["source_id"], unique=False)
    op.create_index(op.f("ix_media_status"), "media", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_status"), table_name="media")
    op.drop_index(op.f("ix_media_source_id"), table_name="media")
    op.drop_index(op.f("ix_media_artifact_id"), table_name="media")
    op.drop_table("media")
    op.drop_table("claim_evidence")
    op.drop_table("artifact_exhibits")
    op.drop_index(op.f("ix_passages_status"), table_name="passages")
    op.drop_index(op.f("ix_passages_source_id"), table_name="passages")
    op.drop_table("passages")
    op.drop_table("exhibit_regions")
    op.drop_index(op.f("ix_claims_status"), table_name="claims")
    op.drop_index(op.f("ix_claims_exhibit_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_artifacts_status"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_source_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_sources_status"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_regions_status"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(op.f("ix_exhibits_status"), table_name="exhibits")
    op.drop_table("exhibits")
    op.drop_index(op.f("ix_reviews_entity_type"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_entity_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
